name: How to use a Windows Runner on GitHub Actions
on: push
runs-on: self-hosted
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Check out repo        
        uses: actions/checkout@v2
      - run: |
          ./net-access-rights.ps1
