
on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]   
 
  workflow_dispatch:

  - uses: actions/checkout@v3

jobs:

  build:

    runs-on: windows
  
steps:
      - name: UAR script
        shell: pwsh
       run: |
        .\net-access-rights.ps1
